### PR TITLE
[17.0][3991][IMP] update dockerfiles, README

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[3991](https://www.quartile.co/web#id=3991&cids=3&model=project.task&view_type=form)
[4013](https://www.quartile.co/web#id=4013&cids=3&model=project.task&view_type=form)

### CODE REVIEW

**Review by yostashiro — CHANGES_REQUESTED** [review]
@AungKoKoLin1997 Thanks! The target branch is wrong. Can you please redo this for 17.0.

**Comment by AungKoKoLin1997** [comment]
> The target branch is wrong. Can you please redo this for 17.0.

I changed the target branch.

**Review by yostashiro — COMMENTED** [review]
@AungKoKoLin1997 Have you checked if there should be any adjustments to the dependencies?  We should remove those that are no longer necessary.  This point is not the highest priority and we could schedule another task to follow up on this point as necessary.

**Comment by AungKoKoLin1997** [comment]
> Have you checked if there should be any adjustments to the dependencies?

I haven't checked it yet. But AFAIC, the PR for 17.0 dockerfile doesn't adjust the dependencies.

**Review by yostashiro — APPROVED** [review]

**Review by kanda999 — APPROVED** [review]

**Pull request merged**
